// Shared styles for all product listing pages
export const S = {
  container: {
    padding: "2rem",
    backgroundColor: "#f5f7fa",
    minHeight: "100vh",
    fontFamily: "'Inter', 'Segoe UI', system-ui, -apple-system, sans-serif",
  },
  content: {
    maxWidth: "1400px",
    margin: "0 auto",
  },
  // ── Loading ──────────────────────────────────────────────
  loadingContainer: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    minHeight: "60vh",
    gap: "1rem",
  },
  spinner: {
    width: "44px",
    height: "44px",
    border: "4px solid #e2e8f0",
    borderTopColor: "#3b82f6",
    borderRadius: "50%",
  },
  loadingText: {
    fontSize: "1rem",
    color: "#64748b",
    fontWeight: 500,
    margin: 0,
  },
  // ── Error ─────────────────────────────────────────────────
  errorContainer: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    minHeight: "60vh",
    gap: "0.75rem",
    padding: "2rem",
  },
  errorIcon: { fontSize: "3rem" },
  errorTitle: {
    fontSize: "1.4rem",
    fontWeight: 600,
    color: "#1e293b",
    margin: 0,
  },
  errorMessage: {
    color: "#64748b",
    fontSize: "1rem",
    textAlign: "center",
    maxWidth: "420px",
    margin: 0,
  },
  // ── Header ────────────────────────────────────────────────
  header: {
    textAlign: "center",
    marginBottom: "2.5rem",
    paddingBottom: "1.5rem",
    borderBottom: "1px solid #e2e8f0",
  },
  pageTitle: {
    fontSize: "2rem",
    fontWeight: 700,
    color: "#1e293b",
    margin: "0 0 0.4rem",
    letterSpacing: "-0.02em",
  },
  pageSubtitle: {
    fontSize: "1rem",
    color: "#64748b",
    fontWeight: 400,
    margin: 0,
  },
  // ── Warning banner ────────────────────────────────────────
  warningBanner: {
    padding: "0.875rem 1.25rem",
    backgroundColor: "#fffbeb",
    border: "1px solid #fde68a",
    borderRadius: "10px",
    marginBottom: "1.5rem",
    color: "#92400e",
    fontSize: "0.875rem",
  },
  // ── Empty state ───────────────────────────────────────────
  emptyState: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    minHeight: "40vh",
    gap: "0.5rem",
    padding: "2rem",
  },
  emptyIcon: { fontSize: "3.5rem", marginBottom: "0.5rem" },
  emptyTitle: {
    fontSize: "1.3rem",
    color: "#1e293b",
    margin: 0,
    fontWeight: 600,
  },
  emptyMessage: {
    fontSize: "0.95rem",
    color: "#64748b",
    margin: 0,
  },
  // ── Card ──────────────────────────────────────────────────
  card: {
    backgroundColor: "#ffffff",
    borderRadius: "16px",
    overflow: "hidden",
    boxShadow: "0 2px 8px rgba(0,0,0,0.07), 0 0 0 1px rgba(0,0,0,0.04)",
    transition: "transform 0.2s ease, box-shadow 0.2s ease",
  },
  imageContainer: {
    position: "relative",
    width: "100%",
    height: "280px",
    overflow: "hidden",
    backgroundColor: "#f8fafc",
  },
  image: {
    width: "100%",
    height: "100%",
    objectFit: "cover",
    transition: "transform 0.3s ease",
  },
  lowStockBadge: {
    position: "absolute",
    top: "10px",
    right: "10px",
    backgroundColor: "#f59e0b",
    color: "#ffffff",
    padding: "0.3rem 0.7rem",
    borderRadius: "20px",
    fontSize: "0.72rem",
    fontWeight: 700,
    letterSpacing: "0.02em",
  },
  outOfStockBadge: {
    position: "absolute",
    top: "10px",
    right: "10px",
    backgroundColor: "#ef4444",
    color: "#ffffff",
    padding: "0.3rem 0.7rem",
    borderRadius: "20px",
    fontSize: "0.72rem",
    fontWeight: 700,
    letterSpacing: "0.02em",
  },
  cardContent: {
    padding: "1.25rem",
  },
  cardHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginBottom: "1rem",
    gap: "0.75rem",
  },
  cardTitle: {
    margin: 0,
    fontSize: "1.05rem",
    fontWeight: 600,
    color: "#1e293b",
    lineHeight: 1.3,
  },
  price: {
    fontSize: "1.2rem",
    fontWeight: 700,
    color: "#10b981",
    whiteSpace: "nowrap",
    flexShrink: 0,
  },
  // ── Variant selectors ─────────────────────────────────────
  variantSection: {
    marginBottom: "1rem",
    paddingBottom: "1rem",
    borderBottom: "1px solid #f1f5f9",
  },
  selectorGroup: {
    marginBottom: "0.875rem",
  },
  selectorLabel: {
    display: "block",
    fontSize: "0.72rem",
    fontWeight: 700,
    color: "#475569",
    marginBottom: "0.4rem",
    textTransform: "uppercase",
    letterSpacing: "0.06em",
  },
  requiredText: {
    fontSize: "0.7rem",
    color: "#ef4444",
    fontWeight: 500,
    marginLeft: "0.4rem",
    textTransform: "none",
    letterSpacing: 0,
  },
  optionButtons: {
    display: "flex",
    flexWrap: "wrap",
    gap: "0.4rem",
  },
  optionButton: {
    padding: "0.35rem 0.8rem",
    border: "1.5px solid #e2e8f0",
    borderRadius: "8px",
    backgroundColor: "#ffffff",
    color: "#334155",
    fontSize: "0.8rem",
    fontWeight: 500,
    cursor: "pointer",
    transition: "all 0.15s",
    lineHeight: 1.5,
    fontFamily: "inherit",
  },
  optionButtonSelected: {
    backgroundColor: "#3b82f6",
    borderColor: "#3b82f6",
    color: "#ffffff",
  },
  optionButtonDisabled: {
    backgroundColor: "#f8fafc",
    borderColor: "#e2e8f0",
    color: "#cbd5e1",
    cursor: "not-allowed",
    textDecoration: "line-through",
    opacity: 0.65,
  },
  // ── Details grid ──────────────────────────────────────────
  detailsGrid: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: "0.75rem",
    marginBottom: "0.875rem",
  },
  detailItem: {
    display: "flex",
    flexDirection: "column",
    gap: "0.2rem",
  },
  detailLabel: {
    fontSize: "0.68rem",
    color: "#94a3b8",
    textTransform: "uppercase",
    fontWeight: 700,
    letterSpacing: "0.06em",
  },
  detailValue: {
    fontSize: "0.875rem",
    color: "#334155",
    fontWeight: 500,
  },
  extraDetails: {
    display: "flex",
    flexWrap: "wrap",
    gap: "0.75rem",
    marginBottom: "1rem",
  },
  extraText: {
    fontSize: "0.825rem",
    color: "#64748b",
  },
  // ── Add to cart button ────────────────────────────────────
  addButton: {
    width: "100%",
    padding: "0.75rem",
    backgroundColor: "#10b981",
    color: "#ffffff",
    border: "none",
    borderRadius: "10px",
    fontSize: "0.875rem",
    fontWeight: 600,
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "0.5rem",
    transition: "background-color 0.2s, transform 0.1s",
    fontFamily: "inherit",
  },
  addButtonDisabled: {
    backgroundColor: "#cbd5e1",
    cursor: "not-allowed",
    transform: "none",
  },
  cartIconStyle: {
    width: "17px",
    height: "17px",
    flexShrink: 0,
  },
};
